language: ruby
rvm:
- 2.2.0
install: bundle install --without development --deployment --jobs=3 --retry=3
cache:
  directories:
  - vendor/bundle
env:
- DB=travis_sqlite
- DB=travis_postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rspec spec
notifications:
  slack:
    secure: ThkVmSGfBzvii5rlm9RRlAYqi0yXcz9icAIe7f08QMxnexlGNW7OMaUqMlqa8Cp608dZbeyUKtrfcBRicxBOeLYA6G4MucMcumlInB1hkARJoSjjqwR+V6LoS4B4baRXe3Ol+NaQptgg3KFdyXFrL+1Fl9yhDCH1j/dmw4SJ2QA=
